### ISSUE TITLE
Curseforge is not a constructor

### ISSUE THREAD

**Issue by jojo2357** [Mondanzo/node-curseforge#1]
I recently needed to upgrade to this version of the CF api in order to query more mods in one page, and just in implemented the MWE, I ran into this pretty big error

```nim
{
  Game: [Getter],
  Mod: [Getter],
  Category: [Getter],
  ModFile: [Getter],
  Types: [Getter],
  Exceptions: [Getter],
  Enums: [Getter],
  default: [Function: Curseforge]
}
TypeError: Curseforge is not a constructor
```

from the following:

```javascript
const Curseforge = require("node-curseforge");
console.log(Curseforge);
const cf = new Curseforge(require("../../config.json").curseforgeToken);
```

Using Webstorm, I found that the import goes fine, 
![image](https://user-images.githubusercontent.com/66704796/157506818-81f7e928-09d8-42c8-9af9-00344cca65a8.png)
but the problem is that it isnt exposed properly? I will look into it if possible.

**Comment by Mondanzo** [comment]
Yeah the import is a bit flunky because multiple things get exported. So you need to use `Curseforge.default()` for now as the constructor

**Comment by jojo2357** [comment]
I believe i tried that, let my look again

**Comment by jojo2357** [comment]
`TypeError: this.set_token is not a function`
`at Object.Curseforge [as default] (.\node_modules\node-curseforge\dist\index.js:65:14)`

from `const cf = Curseforge.default(require("../../config.json").curseforgeToken);`

any workaround known?

**Comment by Mondanzo** [comment]
you still need to use new. So it would be `const cf = new Curseforge.default(require("../../config.json").curseforgeToken);`

**Comment by jojo2357** [comment]
Yeah I figured as much. What is the intended behavior of the import then? Are you going for 

```javascript
const {Curseforge, Mod, Game /* etc */} = require("node-curseforge");
```

or maybe

```javascript
const Curseforge = require("node-curseforge");
const cf = new Curseforge();
const game = new Curseforge.Game();
```

or perhaps some other syntax is desired. I would like to help, but this is your project so I do not want to mess up your design.

**Comment by Mondanzo** [comment]
I should go with the first approach you mentioned, I thought I could just have it export either a constructor or one of the classes but highly doubt it'll work so I'll change it. I also still need to write a hell lot of documentation but didn't really have time to focus much on this project.

**Comment by jojo2357** [comment]
I'll take care of this and the other issue, partly because I need it :joy:, unless you would like to then i wont spoil the fun

**Comment by Mondanzo** [comment]
Feel free to open up a PR! I don't know why the issue is happening for you and I know that I need to write tests, but I'm happy with less work on my side ^^

**Comment by MilleniumModsSources** [comment]
Not sure if this is still active, but I was testing with both example codes and I also get the "Curseforge is not a constructor" error.

`const Curseforge = require("node-curseforge");

const cf_token = "token";

let cf = new Curseforge(cf_token);

let mc = cf.get_game("minecraft");

cf.search_mods(mc).then((mods) => {
    for(let mod of mods){
        cf.get_description(mod).then((desc) => {
            console.log(desc);
        });
    }
});`

**Comment by Mondanzo** [comment]
Yeah it's still relevant and mostly related to me not being too known in writing Typescript libraries.
