### ISSUE TITLE
Latest version (1.2.0) doesn't have any published code.

### ISSUE THREAD

**Issue by SwanX1** [Mondanzo/node-curseforge#11]
When downloading the actual archive from `registry.npmjs.com`, it only contains the following files:
 - .editorconfig
 - LICENSE
 - package.json
 - README.md

File link: [node-curseforge-1.2.0.tgz](https://registry.npmjs.org/node-curseforge/-/node-curseforge-1.2.0.tgz)

This is most likely caused due to the fact that the publishing workflow doesn't have a build step, it only runs `npm ci` and publishes.

**Comment by Mondanzo** [comment]
I'll never understand Github actions.

**Comment by Mondanzo** [comment]
Newest Action does build now and publish properly, I am not happy about the way it does it but it does and that's all that matters.
